[tool.poetry]
name = "cp-3"
version = "0.1.0"
description = ""
authors = ["alexey_zubkov <zubkov.superstar@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^8.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
